project:
  type: website
  output-dir: docs

website:
  title: "Sophia \"Phia\" Ribeiro"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: CV.qmd
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css

editor: visual

